---

- name: Install dependencies
  apt: name=apt-transport-https

- name: Add APT key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key  id=68576280

- name: Add APT repository
  apt_repository: repo="{{item}}" update_cache=yes
  with_items:
  - "deb https://deb.nodesource.com/node_{{nodejs_major_version}} {{ansible_distribution_release}} main"
  - "deb-src https://deb.nodesource.com/node_{{nodejs_major_version}} {{ansible_distribution_release}} main"

- name: Install specific version of nodejs
  apt: name=nodejs={{nodejs_version}}* state='present'
  when: nodejs_version != 'latest'

- name: Install latest version of nodejs
  apt: name=nodejs state='latest'
  when: nodejs_version == 'latest'

# Latest packages doesn't have 'node' executable anymore
# It were renamed to 'nodejs'. Add link to support old
# cookbooks which use the legacy 'node' command.
- stat: path=/usr/bin/node
  register: node_bin

- name: Add legacy node link
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  when: not node_bin.stat.exists
