---

language: python

python:
  - 2.7

install:
  - pip install ansible==1.5.0

script:
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --connection=local --sudo
  - >
    ansible-playbook -i inventory playbook.yml --connection=local --sudo
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
