---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Install nodejs, npm and npm modules
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Fedora
    versions:
    - all
  categories:
  - development
  - system
  - web
