---

php_install:
  - php5
  - php5-intl
  - php5-curl
  - php5-gd
  - php5-mysql
  - php5-pgsql
  - php5-fpm

php_configure:
  - file: /etc/php5/cli/php.ini
    values:
      - { section: PHP, key: upload_max_filesize, value: '20M' }
      - { section: PHP, key: post_max_size, value: '20M' }
      - { section: date, key: date.timezone, value: '{{ timezone }}' }
  - file: /etc/php5/apache2/php.ini
    values:
      - { section: PHP, key: upload_max_filesize, value: '20M' }
      - { section: PHP, key: post_max_size, value: '20M' }
      - { section: date, key: date.timezone, value: '{{ timezone }}' }
